// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomCharts: typeof import('./src/components/datav/BottomCharts.vue')['default']
    CenterCmp: typeof import('./src/components/datav/CenterCmp.vue')['default']
    Datav: typeof import('./src/components/datav/index.vue')['default']
    LabelTag: typeof import('./src/components/datav/LabelTag.vue')['default']
    LeftChart1: typeof import('./src/components/datav/LeftChart1.vue')['default']
    LeftChart2: typeof import('./src/components/datav/LeftChart2.vue')['default']
    LeftChart3: typeof import('./src/components/datav/LeftChart3.vue')['default']
    RightChart1: typeof import('./src/components/datav/RightChart1.vue')['default']
    RightChart2: typeof import('./src/components/datav/RightChart2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
